//
//  CMPConsentV2Constant.h
//  GDPR
//

#ifndef CMPConsentV2Constant_h
#define CMPConsentV2Constant_h

static int VERSION_BIT_OFFSET = 0;
static int VERSION_BIT_LENGTH = 6;

static int CREATED_BIT_OFFSET = 6;
static int CREATED_BIT_LENGTH = 36;

static int LAST_UPDATED_BIT_OFFSET = 42;
static int LAST_UPDATED_BIT_LENGTH = 36;

static int CMP_ID_BIT_OFFSET = 78;
static int CMP_ID_BIT_LENGTH = 12;

static int V2_CMP_VERSION_BIT_OFFSET = 90;
static int V2_CMP_VERSION_BIT_LENGTH = 12;

static int CONSENT_SCREEN_BIT_OFFSET = 102;
static int CONSENT_SCREEN_BIT_LENGTH = 6;

static int CONSENT_LANGUAGE_BIT_OFFSET = 108;
static int CONSENT_LANGUAGE_BIT_LENGTH = 12;

static int VENDOR_LIST_VERSION_BIT_OFFSET = 120;
static int VENDOR_LIST_VERSION_BIT_LENGTH = 12;

static int TCF_POLICY_VERSION_BIT_OFFSET = 132;
static int TCF_POLICY_VERSION_BIT_LENGTH = 6;

static int IS_SERVICE_SPECIFIC_BIT_OFFSET = 138;
static int IS_SERVICE_SPECIFIC_BIT_LENGTH = 1;

static int USE_NON_STANDARD_STACK_BIT_OFFSET = 139;
static int USE_NON_STANDARD_STACK_BIT_LENGTH = 1;

static int SPECIAL_FEATURE_OPT_INS_BIT_OFFSET = 140;
static int SPECIAL_FEATURE_OPT_INS_BIT_LENGTH = 12;

static int PURPOSE_CONSENT_BIT_OFFSET = 152;
static int PURPOSE_CONSENT_BIT_LENGTH = 24;

static int PURPOSE_LI_TRANSPARENCY_BIT_OFFSET = 176;
static int PURPOSE_LI_TRANSPARENCY_BIT_LENGTH = 24;

static int PURPOSE_ONE_TREATMENT_BIT_OFFSET = 200;
static int PURPOSE_ONE_TREATMENT_BIT_LENGTH = 1;

static int PUPBLISHER_CC_BIT_OFFSET = 201;
static int PUPBLISHER_CC_BIT_LENGTH = 12;

static int MAX_VENDOR_BIT_OFFSET = 213;
static int MAX_VENDOR_BIT_LENGTH = 16;

static int MAX_VENDOR_IS_RANGE_ENCODED_BIT_OFFSET = 229;
static int MAX_VENDOR_IS_RANGE_ENCODED_BIT_LENGTH = 1;

static int RANGE_ENTRIES_BIT_LENGTH = 12;

static int NUM_PUB_RESTRICTIONS_BIT_LENGTH = 12;

static int PURPOSE_ID_BIT_LENGTH = 6;
static int RESTRICTION_TYPE_BIT_LENGTH = 2;

static int SEGMENT_TYPE_BIT_OFFSET = 0;
static int SEGMENT_TYPE_BIT_LENGTH = 3;

static int PUB_PURPOSE_CONSENTS_BIT_OFFSET = 3;
static int PUB_PURPOSE_CONSENTS_BIT_LENGTH = 24;

static int PUB_PURPOSE_LI_TRANSPARENCY_BIT_OFFSET = 27;
static int PUB_PURPOSE_LI_TRANSPARENCY_BIT_LENGTH = 24;

static int NUM_CUSTOM_PURPOSES_BIT_OFFSET = 51;
static int NUM_CUSTOM_PURPOSES_BIT_LENGTH = 6;

#endif /* CMPConsentConstant_h */
